name: Second Testing Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Job_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "1 - Hello World ğŸ”¥ï¸"

  Job_2:
    runs-on: ubuntu-latest
    needs: Job_1
    steps:
      - run: echo "2 - Hello World ğŸ”¥ï¸"

  Job_3:
    needs: Job_1
    runs-on: ubuntu-latest
    steps:
      - run: echo "3 - Hello World ğŸ”¥ï¸"

  Job_4:
    runs-on: ubuntu-latest
    needs: [Job_2, Job_3]
    steps:
      - run: echo "4 - Hello World ğŸ”¥ï¸"
